props=[
  {"rental":"False","pid":"735","created":"2015-10-29 13:41:49.448830",
  "lastedited":"2015-02-28 17:20:04","ref":"AP2LF006","price":"105000",
  "originalprice":"0","frequency":"sale","ptype":"Apartment",
  "town":"Guardamar del Segura","province":"Alicante","location":"Algorfa","beds":"2",
  "baths":"2","pool":"yes","description":"WONDERFUL KEYREADY GROUNDFLOOR APARTMENT in LA FINCA golf course near Algorfa. It's a great area close to all facilities of Ciudad Quesada, Almoradi and the greater Torrevieja/Guardamar area, i.e. lots of restaurants, shopping centres, the beaches, all water sports plus golf and more.","DE":"Wunderbare schlüsselfertig Erdgeschosswohnung in LA FINCA Golfplatz in der Nähe Algorfa. Es ist eine großartige Gegend in der Nähe zu allen Einrichtungen von Ciudad Quesada, Almoradi und desto größer ist Torrevieja / Guardamar Bereich, dh viele Restaurants, Einkaufszentren, Strände, alle Wassersportarten sowie Golf und vieles mehr.",
  "NL":"Bijzonder mooi sleutel-op-de-deurappartement op de eerste verdieping in het golfgebied van La Finca, Algorfa. Het is een groot golfgebied, dicht bij alle faciliteiten van Ciudad Quesada, Almoradi, Torrevieja en Guardamar. Je vindt er vele restaurants, winkeltjes, stranden, golf, watersportactiviteiten, en meer.","display":"True","offplan":"False","living":"81",
  "plot":"0","fireplace":"True","heating":"False",
  "aircon":"False","kitchen":"open","utility":"True",
  "solarium":"False","balconies":"No","furnished":"yes",
  "topsix":"False","salestage":"0","beach":"False",
  "golf":"True","luxury":"False","finca":"False","penthouse":"False","EUR":""},
  {"rental":"False","pid":"762","created":"2015-10-29 13:41:49.473389",
  "lastedited":"2015-03-25 15:06:04","ref":"DH5-Fin022","price":"1300000",
  "originalprice":"2250000","frequency":"sale","ptype":"Finca",
  "town":"Orihuela","province":"Alicante","location":"Orihuela","beds":"5",
  "baths":"2","pool":"yes","description":"A UNIQUE luxury finca in the area of Orihuela which must be seen as words are not enough. The property offers a large pool area, jacuzzi, patio area, summer kitchen, spacious lounge, bodega, a spacious 400 sqm living area. as well as the main house you will have 2 separate houses each with with 100 sqm of living space. the properties are surrounded by 1,000 sqm of lovely landscaped Spanish garden.","DE":"Eine einzigartige luxuriöse Finca in der Nähe von Orihuela - Worte sind nicht genug um das Traumheim zu beschreiben. Das Anwesen bietet einen großen Pool, Jacuzzi, Terrasse, Sommerküche, großzügige Lounge/Wohnbereiche, Weinkeller, eine sehr großzügige 400 qm Wohnfläche. Neben dem Haupthaus haben Sie 2 separate Häuser mit je mit 100 qm Wohnfläche zusätzlich. Die Immobilie ist von einem ca. 1.000 qm herrlich angelegten spanischen Garten umgeben.",
  "NL":"Een unieke luxueuze finca op een grondstuk van liefst 1000m² in de buurt van Orihuela die u echt met eigen ogen moet zien. De woning (opp. 400m²) heeft een groot zwembad, jacuzzi, een patio, een buitenkeuken, een ruime woonkamer en een bodega. Naast de hoofdwoning heb je ook twee aparte woningen die elk een opp. van 100m² hebben. Rondom bevindt zich een schitterende Spaanse aangelegde tuin.","display":"True","offplan":"False","living":"600",
  "plot":"5700","fireplace":"True","heating":"True",
  "aircon":"False","kitchen":"separate","utility":"True",
  "solarium":"True","balconies":"No","furnished":"yes",
  "topsix":"False","salestage":"0","beach":"False",
  "golf":"False","luxury":"False","finca":"False","penthouse":"False","EUR":""}
]
yaba